<?php defined('ABSPATH') || exit; ?>
<!doctype html>
<html <?php language_attributes(); ?>><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title><?php echo esc_html__('Sign in | Fandoogh Rest', 'fandoogh-rest'); ?></title>
<style>body{margin:0;min-height:100vh;display:grid;place-items:center;background:#f5f1eb;color:#282723;font-family:Tahoma,sans-serif}.login{width:min(360px,calc(100vw - 64px));background:#fff;padding:32px;border-radius:24px;box-shadow:0 20px 80px #4d38200d}.brand{color:#a65a35;font-size:15px;letter-spacing:1px}h1{font-size:25px;margin:18px 0 8px}p{font-size:13px;line-height:2;color:#77746e}label{display:block;margin-top:18px;font-size:13px}input:not([type=checkbox]){box-sizing:border-box;width:100%;border:1px solid #e6e1da;border-radius:12px;padding:13px;margin-top:8px;font:inherit}input:focus{outline:2px solid #c87545;outline-offset:2px}button{width:100%;padding:14px;border:0;border-radius:12px;background:#a65a35;color:#fff;font:inherit;margin-top:24px;cursor:pointer}.error{background:#fff1ee;color:#a43221;border-radius:12px;padding:12px}.check{display:flex;align-items:center;gap:8px}a{color:#a65a35;text-decoration:none}</style></head>
<body><main class="login"><div class="brand"><?php echo esc_html__('Fandoogh Rest / WORKSPACE', 'fandoogh-rest'); ?></div><h1><?php echo esc_html__('Welcome to your restaurant panel', 'fandoogh-rest'); ?></h1><p><?php echo esc_html(\FandooghRest\Core\Settings::get('restaurant_name')); ?> · <?php echo esc_html__('Menu and order management', 'fandoogh-rest'); ?></p>
<?php if ($error): ?><p class="error" role="alert"><?php echo esc_html($error); ?></p><?php endif; ?>
<form method="post" action="<?php echo esc_url(\FandooghRest\Core\Settings::panelUrl()); ?>">
<?php wp_nonce_field('admincafe_login'); ?>
<label for="username"><?php echo esc_html__('Username or email', 'fandoogh-rest'); ?></label><input id="username" name="username" autocomplete="username" required autofocus maxlength="254">
<label for="password"><?php echo esc_html__('Password', 'fandoogh-rest'); ?></label><input id="password" name="password" type="password" autocomplete="current-password" required maxlength="1024">
<label class="check"><input type="checkbox" name="remember" value="1"><?php echo esc_html__('Remember me', 'fandoogh-rest'); ?></label><button type="submit"><?php echo esc_html__('Sign in to panel', 'fandoogh-rest'); ?></button>
</form><p><a href="<?php echo esc_url(wp_lostpassword_url(\FandooghRest\Core\Settings::panelUrl())); ?>"><?php echo esc_html__('Reset password', 'fandoogh-rest'); ?></a> · <a href="<?php echo esc_url(\FandooghRest\Core\Settings::menuUrl()); ?>"><?php echo esc_html__('View menu', 'fandoogh-rest'); ?></a></p></main></body></html>
