import { mkdir, readFile, writeFile, copyFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { messages } from '../frontend/src/i18n.js';
import { dictionaries } from '../frontend/src/customer-i18n.js';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const phpQuote = value => "'" + value.replaceAll('\\', '\\\\').replaceAll("'", "\\'") + "'";
await mkdir(resolve(root, 'resources'), { recursive: true });
await writeFile(resolve(root, 'resources/customer-strings.json'), JSON.stringify(dictionaries, null, 2) + '\n', 'utf8');
await writeFile(resolve(root, 'resources/ui-strings.php'),
  '<?php\n// Generated by scripts/stage.mjs from the UI translation catalog.\ndefined(\'ABSPATH\') || exit;\nreturn [\n' +
  messages.map(message => '    ' + phpQuote(message) + ' => __(' + phpQuote(message) + ", 'fandoogh-rest'),").join('\n') + '\n];\n', 'utf8');
await mkdir(resolve(root, 'assets'), { recursive: true });
await copyFile(resolve(root, 'resources/builder-block.js'), resolve(root, 'assets/builder-block.js'));
await copyFile(resolve(root, 'frontend/FONT-LICENSE.txt'), resolve(root, 'assets/FONT-LICENSE.txt'));
console.log(`Staged builder editor and ${messages.length} translatable UI labels.`);
